apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scparticles.ops.example.org
spec:
  group: ops.example.org
  names:
    kind: SCPArtifact
    listKind: SCPArtifactList
    plural: scparticles
    singular: scparticle
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["host","username","authRef","source","destinationPath"]
              properties:
                host: { type: string }
                port: { type: integer, minimum: 1, maximum: 65535, default: 22 }
                username: { type: string }
                authRef:
                  type: object
                  properties:
                    name: { type: string }
                    key: { type: string }
                  required: ["name"]
                source:
                  type: object
                  properties:
                    httpUrl: { type: string }
                    inline:
                      type: object
                      properties:
                        base64: { type: string }
                    configMapRef:
                      type: object
                      properties:
                        name: { type: string }
                        key: { type: string }
                destinationPath: { type: string }
                strictHostKeyChecking: { type: boolean, default: true }
                knownHostsRef:
                  type: object
                  properties:
                    name: { type: string }
                    key: { type: string }
                connectTimeoutMillis: { type: integer, minimum: 1, default: 10000 }
                sessionTimeoutMillis: { type: integer, minimum: 1, default: 10000 }
            status:
              type: object
              properties:
                phase: { type: string }
                message: { type: string }
                lastTransferTime: { type: string }
                bytesTransferred: { type: integer }
                checksum: { type: string }
      subresources:
        status: {}
