apiVersion: v1
kind: ServiceAccount
metadata:
  name: scp-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scp-operator
rules:
  - apiGroups: ["ops.example.org"]
    resources: ["scparticles","scparticles/status"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources: ["secrets","configmaps","events"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scp-operator
subjects:
  - kind: ServiceAccount
    name: scp-operator
    namespace: default
